version: '3.8'

services:
  backend:
    build: ./Organoid-Review-Backend
    mac_address: f2:6d:ac:ef:2d:1d
    ports:
      - "5000:5000"
    volumes:
      - ./Organoid-Review-Backend:/app
      - ${DATA_PATH_HOST}:/app/data
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=organoid123
      - DB_NAME=organoid-db

    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: organoid123
      MYSQL_DATABASE: organoid-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  frontend:
    build:
      context: ./Organoid-Review-Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Organoid-Review-Frontend:/app           # Mapuje Twój kod do kontenera (dla hot-reloading)
      - /app/node_modules         # Zapobiega nadpisaniu node_modules wewnątrz kontenera przez pusty folder z hosta
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ważne dla Windows/WSL, aby wykrywać zmiany w plikach
      # Tu możesz dodać zmienne środowiskowe, np. adres backendu:
      - VITE_API_URL=http://localhost:5000/
    depends_on:
      - backend                   # Frontend uruchomi się po backendzie
    stdin_open: true              # Potrzebne, aby proces Reacta nie zamykał się od razu
    tty: true
volumes:
  db_data: