version: '3.8'

services:
  backend:
    build: ./Organoid-Review-Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Organoid-Review-Backend:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=organoid123
      - DB_NAME=organoid-db
    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: organoid123
      MYSQL_DATABASE: organoid-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: